version: '3.4'
services:
  nebula-metad:
    image: vesoft/nebula-metad:v3.2.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=nebula-metad:9559
      - --local_ip=nebula-metad
      - --ws_ip=nebula-metad
      - --port=9559
      - --ws_http_port=19559
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://nebula-metad:19559/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "9559:9559"
      - "19559:19559"
      - "19560:19560"
    volumes:
      - ${DOCKER_VOLUME_DIR}/nebula-metad:/data/meta
      - ${DOCKER_VOLUME_DIR}/nebula-metad-logs:/logs
    restart: always
    cap_add:
      - SYS_PTRACE

  nebula-storaged:
    image: vesoft/nebula-storaged:v3.2.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=nebula-metad:9559
      - --local_ip=nebula-storaged
      - --ws_ip=nebula-storaged
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    depends_on:
      - nebula-metad
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://nebula-storaged:19779/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "9779:9779"
      - "19779:19779"
      - "19780:19780"
    volumes:
      - ${DOCKER_VOLUME_DIR}/nebula-storaged:/data/storage
      - ${DOCKER_VOLUME_DIR}/nebula-storaged-logs:/logs
    restart: always
    cap_add:
      - SYS_PTRACE

  nebula-graphd:
    image: vesoft/nebula-graphd:v3.2.0
    environment:
      USER: root
      TZ:   "${TZ}"
    command:
      - --meta_server_addrs=nebula-metad:9559
      - --port=9669
      - --local_ip=nebula-graphd
      - --ws_ip=nebula-graphd
      - --ws_http_port=19669
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    depends_on:
      - nebula-storaged
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://nebula-graphd:19669/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "9669:9669"
      - "19669:19669"
      - "19670:19670"
    volumes:
      - ${DOCKER_VOLUME_DIR}/nebula-graph-logs:/logs
    restart: always
    cap_add:
      - SYS_PTRACE

  nebula-console:
    image: vesoft/nebula-console:v3.0.0
    entrypoint: ""
    command:
      - sh
      - -c
      - |
        sleep 3 &&
        nebula-console -addr nebula-graphd -port 9669 -u root -p nebula -e 'ADD HOSTS "nebula-storaged":9779' &&
        sleep 36000
    depends_on:
      - nebula-graphd

  nebula-graph-studio:
    image: vesoft/nebula-graph-studio:v3.4.1
    restart: always
    environment:
      USER: root
    ports:
      - "7001:7001"